/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.ConexaoBD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author peter
 */
public class MateriaisTela extends javax.swing.JFrame {

    /**
     * Creates new form MateriaisTela
     */
    public MateriaisTela() {
        initComponents();
        habilitaBtn(true);

        jtfId.setEnabled(false);
        habilitaTextField(false);
        jtfValor.setText("R$: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfId = new javax.swing.JTextField();
        jtfMaterial = new javax.swing.JTextField();
        jtfQtd = new javax.swing.JTextField();
        jtfObra = new javax.swing.JTextField();
        jtfResponsavel = new javax.swing.JTextField();
        jtfCidadeEstado = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jtfTelefoneForn = new javax.swing.JFormattedTextField();
        jtfDataCompra = new javax.swing.JFormattedTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaMateriais = new javax.swing.JTable();
        jButtonDados = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jtfBuscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckQtd = new javax.swing.JCheckBox();
        jCheckKg = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RZM Construtora - Materiais");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 40));
        getContentPane().add(jtfMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 230, 40));
        getContentPane().add(jtfQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 230, 40));
        getContentPane().add(jtfObra, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 230, 40));
        getContentPane().add(jtfResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 230, 40));
        getContentPane().add(jtfCidadeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 200, 40));
        getContentPane().add(jtfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 230, 40));
        getContentPane().add(jtfValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 350, 120, 40));

        try {
            jtfTelefoneForn.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtfTelefoneForn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 230, 40));

        try {
            jtfDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtfDataCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 200, 40));

        jButtonNovo.setContentAreaFilled(false);
        jButtonNovo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 150, 50));

        jButtonCancelar.setContentAreaFilled(false);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 150, 50));

        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 140, 50));

        jButtonAtualizar.setContentAreaFilled(false);
        jButtonAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 140, 50));

        jButtonExcluir.setContentAreaFilled(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, 60, 50));

        jTabelaMateriais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Material", "Quantidade", "Data de Compra", "Telefone Fornecedor", "Responsvel", "Cidade-Estado", "Endereço", "Obra", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTabelaMateriais);
        if (jTabelaMateriais.getColumnModel().getColumnCount() > 0) {
            jTabelaMateriais.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 900, 130));

        jButtonDados.setText("DADOS");
        jButtonDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 90, 30));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, 80, 30));
        getContentPane().add(jtfBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 420, 90, 30));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Digite o ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 80, 30));

        jCheckQtd.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jCheckQtd.setForeground(new java.awt.Color(0, 0, 0));
        jCheckQtd.setText("Quantidade");
        jCheckQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckQtdActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckQtd, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jCheckKg.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jCheckKg.setForeground(new java.awt.Color(0, 0, 0));
        jCheckKg.setText("Kg.");
        jCheckKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckKgActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckKg, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RZM (Materiais.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDadosActionPerformed
        try {

            String sql = "select * from materiais";

            PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

            ResultSet rs = stm.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) jTabelaMateriais.getModel();

            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("material"),
                    rs.getString("quantidade"),
                    rs.getString("dataCompra"),
                    rs.getString("telefoneFornecedor"),
                    rs.getString("responsavel"),
                    rs.getString("cidadeEstado"),
                    rs.getString("endereco"),
                    rs.getString("obra"),
                    rs.getString("valor")
                });

            }

            rs.close();
            stm.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro" + e);
        }
    }//GEN-LAST:event_jButtonDadosActionPerformed

    private void jCheckKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckKgActionPerformed
        jCheckQtd.setSelected(false);
        jtfQtd.setText("kg: ");
    }//GEN-LAST:event_jCheckKgActionPerformed

    private void jCheckQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckQtdActionPerformed
        jCheckKg.setSelected(false);
        jtfQtd.setText("Qtd: ");
    }//GEN-LAST:event_jCheckQtdActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        habilitaBtn(true);
        habilitaTextField(false);

        try {

            String sql = "INSERT INTO materiais "
                    + "(material,"
                    + " quantidade, "
                    + "dataCompra, "
                    + "telefoneFornecedor, "
                    + "responsavel, "
                    + "cidadeEstado, "
                    + "endereco, "
                    + "obra, "
                    + "valor) VALUES (?,?,?,?,?,?,?,?,?)";

            PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

            stm.setString(1, jtfMaterial.getText());
            stm.setString(2, jtfQtd.getText());
            stm.setString(3, jtfDataCompra.getText());
            stm.setString(4, jtfTelefoneForn.getText());
            stm.setString(5, jtfResponsavel.getText());
            stm.setString(6, jtfCidadeEstado.getText());
            stm.setString(7, jtfEndereco.getText());
            stm.setString(8, jtfObra.getText());
            stm.setString(9, jtfValor.getText());

            stm.execute();
            stm.close();

            JOptionPane.showMessageDialog(null, "cadastrado no BD");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro ao gravar " + e);
        }

    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        habilitaBtn(false);
        habilitaTextField(true);
        limparCampoForm();
        jtfMaterial.requestFocus();
        jtfId.setText("");
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampoForm();
        habilitaBtn(true);
        habilitaTextField(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        habilitaBtn(false);
        habilitaTextField(true);
        jtfMaterial.requestFocus();

        if (jtfId.equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o ID");
        } else {
            try {

                String sql = "UPDATE materiais set "
                        + "material=?, "
                        + "quantidade=?, "
                        + "dataCompra=?, "
                        + "telefoneFornecedor=?, "
                        + "responsavel=?, "
                        + "cidadeEstado=?, "
                        + "endereco=?, "
                        + "obra=?, "
                        + "valor=? where id=?";

                PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

                stm.setString(1, jtfMaterial.getText());
                stm.setString(2, jtfQtd.getText());
                stm.setString(3, jtfDataCompra.getText());
                stm.setString(4, jtfTelefoneForn.getText());
                stm.setString(5, jtfResponsavel.getText());
                stm.setString(6, jtfCidadeEstado.getText());
                stm.setString(7, jtfEndereco.getText());
                stm.setString(8, jtfObra.getText());
                stm.setString(9, jtfValor.getText());
                stm.setString(10, jtfId.getText());

                stm.execute();
                stm.close();

                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Erro ao atualizar " + e);
            }

        }
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        if (jtfId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o ID");
        } else {
            try {

                String sql = "DELETE from materiais WHERE id=?";

                PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

                stm.setString(1, jtfId.getText());

                stm.execute();
                stm.close();
                JOptionPane.showMessageDialog(null, "Excluído com Sucesso!");
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Informe o ID a ser excluído!" + e);
            }
        }
        limparCampoForm();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        habilitaTextField(true);
        if (jtfBuscar.equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o ID para a busca!");
        } else {
            try {

                String sql = "select * from materiais where id like ?";

                PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

                stm.setString(1, "%" + jtfBuscar.getText());

                ResultSet rs = stm.executeQuery();

                while (rs.next()) {
                    jtfId.setText(rs.getString("id"));
                    jtfMaterial.setText(rs.getString("material"));
                    jtfQtd.setText(rs.getString("quantidade"));
                    jtfDataCompra.setText(rs.getString("dataCompra"));
                    jtfTelefoneForn.setText(rs.getString("telefoneFornecedor"));
                    jtfResponsavel.setText(rs.getString("responsavel"));
                    jtfCidadeEstado.setText(rs.getString("cidadeEstado"));
                    jtfEndereco.setText(rs.getString("endereco"));
                    jtfObra.setText(rs.getString("obra"));
                    jtfValor.setText(rs.getString("valor"));
                }

                rs.close();
                stm.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Erro" + e);
            }
        }

    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MateriaisTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MateriaisTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MateriaisTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MateriaisTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MateriaisTela().setVisible(true);
            }
        });
    }

    public void habilitaBtn(boolean estado) {
        jButtonNovo.setEnabled(estado);
        jButtonAtualizar.setEnabled(estado);
        jButtonExcluir.setEnabled(estado);
        jButtonSalvar.setEnabled(!estado);
        jButtonCancelar.setEnabled(!estado);
    }

    public void habilitaTextField(boolean estado) {
        jtfQtd.setEnabled(estado);
        jtfMaterial.setEnabled(estado);
        jCheckQtd.setEnabled(estado);
        jtfCidadeEstado.setEnabled(estado);
        jCheckKg.setEnabled(estado);
        jtfEndereco.setEnabled(estado);
        jtfTelefoneForn.setEnabled(estado);
        jtfDataCompra.setEnabled(estado);
        jtfResponsavel.setEnabled(estado);
        jtfObra.setEnabled(estado);
        jtfValor.setEnabled(estado);
    }

    public void limparCampoForm() {
        jtfMaterial.setText("");   
        jtfCidadeEstado.setText("");     
        jtfEndereco.setText("");
        jtfTelefoneForn.setText("");
        jtfDataCompra.setText("");
        jtfResponsavel.setText("");
        jtfObra.setText("");
        jtfValor.setText("");
        jtfQtd.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    public javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    public javax.swing.JButton jButtonDados;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JCheckBox jCheckKg;
    private javax.swing.JCheckBox jCheckQtd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabelaMateriais;
    public javax.swing.JTextField jtfBuscar;
    public javax.swing.JTextField jtfCidadeEstado;
    public javax.swing.JFormattedTextField jtfDataCompra;
    public javax.swing.JTextField jtfEndereco;
    public javax.swing.JTextField jtfId;
    public javax.swing.JTextField jtfMaterial;
    public javax.swing.JTextField jtfObra;
    public javax.swing.JTextField jtfQtd;
    public javax.swing.JTextField jtfResponsavel;
    public javax.swing.JFormattedTextField jtfTelefoneForn;
    public javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
