/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import dao.ConexaoBD;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author peter
 */
public class ObrasTela extends javax.swing.JFrame {

    /**
     * Creates new form ObrasTela
     */
    public ObrasTela() {
        initComponents();

        habilitaBtn(true);
        jtfId.setEnabled(false);
        habilitaTextField(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtfId = new javax.swing.JTextField();
        jtfNomeProp = new javax.swing.JTextField();
        jtfDataInicio = new javax.swing.JFormattedTextField();
        jtfPrevisao = new javax.swing.JFormattedTextField();
        jtfTelefoneProp = new javax.swing.JFormattedTextField();
        jtfCep = new javax.swing.JFormattedTextField();
        jtfEmail = new javax.swing.JTextField();
        jtfCidadeEstado = new javax.swing.JTextField();
        jtfEndereco = new javax.swing.JTextField();
        jtfEngenheiro = new javax.swing.JTextField();
        jtfSupervisor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabelaObras = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfBusca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        fundoObras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RZM Construtora - Obras");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jtfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 70, 40));
        getContentPane().add(jtfNomeProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 510, 40));

        try {
            jtfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDataInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jtfDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, 40));

        try {
            jtfPrevisao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtfPrevisao, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 200, 40));

        try {
            jtfTelefoneProp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtfTelefoneProp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, 220, 40));

        try {
            jtfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 190, 40));
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 190, 40));
        getContentPane().add(jtfCidadeEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 200, 40));
        getContentPane().add(jtfEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 220, 40));
        getContentPane().add(jtfEngenheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 200, 40));
        getContentPane().add(jtfSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 220, 40));

        jTabelaObras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Proprietário", "Data Inicio", "Previsão término", "Telefone", "Email", "Cidade-Estado", "Endereço", "CEP", "Engenheiro", "Supervisor"
            }
        ));
        jScrollPane1.setViewportView(jTabelaObras);
        if (jTabelaObras.getColumnModel().getColumnCount() > 0) {
            jTabelaObras.getColumnModel().getColumn(0).setPreferredWidth(20);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 900, 140));

        jButtonNovo.setContentAreaFilled(false);
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 150, 50));

        jButtonCancelar.setContentAreaFilled(false);
        jButtonCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 590, 150, 50));

        jButtonSalvar.setContentAreaFilled(false);
        jButtonSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 590, 150, 50));

        jButtonAtualizar.setContentAreaFilled(false);
        jButtonAtualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 590, 150, 50));

        jButtonExcluir.setContentAreaFilled(false);
        jButtonExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, 60, 50));

        jButton1.setText("DADOS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 418, 80, 30));

        jLabel1.setForeground(new java.awt.Color(153, 204, 255));
        jLabel1.setText("Digite o ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 80, 30));
        getContentPane().add(jtfBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 420, 80, -1));

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, -1, -1));

        fundoObras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RZM Obras.png"))); // NOI18N
        getContentPane().add(fundoObras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDataInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDataInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDataInicioActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        habilitaBtn(false);
        habilitaTextField(true);
        limparCampoForm();
        jtfNomeProp.requestFocus();
        jtfId.setText("");

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        limparCampoForm();
        habilitaBtn(true);
        habilitaTextField(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        habilitaBtn(true);
        habilitaTextField(false);

        try {

            String sql = "INSERT INTO obras (nomePropietario, dataInicio, previsaoTermino, telefonePropietario, emailPropietario, cidadeEstado, endereco, cep, engenheiro, supervisor) VALUES (?,?,?,?,?,?,?,?,?,?)";

            PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

            stm.setString(1, jtfNomeProp.getText());
            stm.setString(2, jtfDataInicio.getText());
            stm.setString(3, jtfPrevisao.getText());
            stm.setString(4, jtfTelefoneProp.getText());
            stm.setString(5, jtfEmail.getText());
            stm.setString(6, jtfCidadeEstado.getText());
            stm.setString(7, jtfEndereco.getText());
            stm.setString(8, jtfCep.getText());
            stm.setString(9, jtfEngenheiro.getText());
            stm.setString(10, jtfSupervisor.getText());

            stm.execute();
            stm.close();

            JOptionPane.showMessageDialog(null, "cadastrado no BD");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro ao gravar " + e);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        habilitaBtn(false);
        habilitaTextField(true);
        jtfNomeProp.requestFocus();

        if (jtfId.equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o ID");
        } else {
            try {

                String sql = "UPDATE obras set nomePropietario=?,"
                        + " dataInicio=?,"
                        + " previsaoTermino=?,"
                        + " telefonePropietario=?,"
                        + " emailPropietario=?,"
                        + " cidadeEstado=?,"
                        + " endereco=?,"
                        + " cep=?,"
                        + " engenheiro=?,"
                        + " supervisor=? where id=?";

                PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

                stm.setString(1, jtfNomeProp.getText());
                stm.setString(2, jtfDataInicio.getText());
                stm.setString(3, jtfPrevisao.getText());
                stm.setString(4, jtfTelefoneProp.getText());
                stm.setString(5, jtfEmail.getText());
                stm.setString(6, jtfCidadeEstado.getText());
                stm.setString(7, jtfEndereco.getText());
                stm.setString(8, jtfCep.getText());
                stm.setString(9, jtfEngenheiro.getText());
                stm.setString(10, jtfSupervisor.getText());
                stm.setString(11, jtfId.getText());

                stm.execute();
                stm.close();

                JOptionPane.showMessageDialog(null, "Atualizado com sucesso!");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Erro ao atualizar " + e);
            }

        }

    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
         if (jtfId.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o ID");
        } else {
            try {

                String sql = "DELETE from obras WHERE id=?";

                PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

                stm.setString(1, jtfId.getText());

                stm.execute();
                stm.close();
                JOptionPane.showMessageDialog(null, "Excluído com Sucesso!");
            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Informe o ID a ser excluído!" + e);
            }
        }
        limparCampoForm();
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String sql = "select * from obras";

            PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

            ResultSet rs = stm.executeQuery();

            DefaultTableModel modelo = (DefaultTableModel) jTabelaObras.getModel();

            modelo.setNumRows(0);

            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("nomePropietario"),
                    rs.getString("dataInicio"),
                    rs.getString("previsaoTermino"),
                    rs.getString("telefonePropietario"),
                    rs.getString("emailPropietario"),
                    rs.getString("cidadeEstado"),
                    rs.getString("endereco"),
                    rs.getString("cep"),
                    rs.getString("engenheiro"),
                    rs.getString("supervisor")
                });

            }

            rs.close();
            stm.close();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Erro" + e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        habilitaTextField(true);
        if (jtfBusca.equals("")) {
            JOptionPane.showMessageDialog(null, "Informe o ID para a busca!");
        } else {
            try {

                String sql = "select * from obras where id like ?";

                PreparedStatement stm = ConexaoBD.abreConexao().prepareStatement(sql);

                stm.setString(1, "%" + jtfBusca.getText());

                ResultSet rs = stm.executeQuery();

                while (rs.next()) {
                    jtfId.setText(rs.getString("id"));
                    jtfNomeProp.setText(rs.getString("nomePropietario"));
                    jtfDataInicio.setText(rs.getString("dataInicio"));
                    jtfPrevisao.setText(rs.getString("previsaoTermino"));
                    jtfTelefoneProp.setText(rs.getString("telefonePropietario"));
                    jtfEmail.setText(rs.getString("emailPropietario"));
                    jtfCidadeEstado.setText(rs.getString("cidadeEstado"));
                    jtfEndereco.setText(rs.getString("endereco"));
                    jtfCep.setText(rs.getString("cep"));
                    jtfEngenheiro.setText(rs.getString("engenheiro"));
                    jtfSupervisor.setText(rs.getString("supervisor"));
                }

                rs.close();
                stm.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Erro" + e);
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ObrasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ObrasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ObrasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ObrasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ObrasTela().setVisible(true);
            }
        });
    }

    public void habilitaBtn(boolean estado) {
        jButtonNovo.setEnabled(estado);
        jButtonAtualizar.setEnabled(estado);
        jButtonExcluir.setEnabled(estado);
        jButtonSalvar.setEnabled(!estado);
        jButtonCancelar.setEnabled(!estado);
    }

    public void habilitaTextField(boolean estado) {
        jtfNomeProp.setEnabled(estado);
        jtfDataInicio.setEnabled(estado);
        jtfCidadeEstado.setEnabled(estado);
        jtfEmail.setEnabled(estado);
        jtfEndereco.setEnabled(estado);
        jtfTelefoneProp.setEnabled(estado);
        jtfPrevisao.setEnabled(estado);
        jtfCep.setEnabled(estado);
        jtfEngenheiro.setEnabled(estado);
        jtfSupervisor.setEnabled(estado);
    }

    public void limparCampoForm() {
        jtfNomeProp.setText("");
        jtfDataInicio.setText("");
        jtfPrevisao.setText("");
        jtfCidadeEstado.setText("");
        jtfEmail.setText("");
        jtfEndereco.setText("");
        jtfTelefoneProp.setText("");
        jtfCep.setText("");
        jtfEngenheiro.setText("");
        jtfSupervisor.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fundoObras;
    private javax.swing.JButton jButton1;
    public javax.swing.JButton jButtonAtualizar;
    public javax.swing.JButton jButtonBuscar;
    public javax.swing.JButton jButtonCancelar;
    public javax.swing.JButton jButtonExcluir;
    public javax.swing.JButton jButtonNovo;
    public javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTabelaObras;
    public javax.swing.JTextField jtfBusca;
    public javax.swing.JFormattedTextField jtfCep;
    public javax.swing.JTextField jtfCidadeEstado;
    public javax.swing.JFormattedTextField jtfDataInicio;
    public javax.swing.JTextField jtfEmail;
    public javax.swing.JTextField jtfEndereco;
    public javax.swing.JTextField jtfEngenheiro;
    public javax.swing.JTextField jtfId;
    public javax.swing.JTextField jtfNomeProp;
    public javax.swing.JFormattedTextField jtfPrevisao;
    public javax.swing.JTextField jtfSupervisor;
    public javax.swing.JFormattedTextField jtfTelefoneProp;
    // End of variables declaration//GEN-END:variables
}
