/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import Calculos.CalcularContraPiso;
import Calculos.Reboco;
import Calculos.AlvenariaTela;


/**
 *
 * @author peter
 */
public class TelaInicial extends javax.swing.JFrame {
    
    //construtor
    public TelaInicial() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonFuncionarios = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonObras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonFerramentas = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonMateriais = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonCalcularAlvenaria = new javax.swing.JButton();
        jButtonContrapiso = new javax.swing.JButton();
        jButtonReboco = new javax.swing.JButton();
        jDesktop = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("RZM Construtora");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Funcionários");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 90, 20));

        jButtonFuncionarios.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jButtonFuncionarios.setForeground(new java.awt.Color(0, 0, 0));
        jButtonFuncionarios.setContentAreaFilled(false);
        jButtonFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFuncionariosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 120));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone 2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 100));

        jButtonObras.setContentAreaFilled(false);
        jButtonObras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonObras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonObrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonObras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 120));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone 4.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 110, 100));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Obras");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 80, 20));

        jButtonFerramentas.setContentAreaFilled(false);
        jButtonFerramentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonFerramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFerramentasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFerramentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 140, 130));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone 3.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, 110));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Ferramentas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 100, 20));

        jButtonMateriais.setContentAreaFilled(false);
        jButtonMateriais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMateriais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMateriaisActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMateriais, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 130, 110));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icone 1.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 110, 100));

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Materiais");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, 70, -1));

        jButtonCalcularAlvenaria.setText("Calcular Alvenaria");
        jButtonCalcularAlvenaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalcularAlvenariaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalcularAlvenaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 60, 130, 90));

        jButtonContrapiso.setText("Calcular Contrapiso");
        jButtonContrapiso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContrapisoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContrapiso, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 190, 140, 90));

        jButtonReboco.setText("Calcular Reboco");
        jButtonReboco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRebocoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReboco, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, 120, 90));

        jDesktop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fundo.jpeg"))); // NOI18N
        getContentPane().add(jDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //instanciando a classe FuncionariosTela através do botão e deixando o jFrame visivel
    private void jButtonFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFuncionariosActionPerformed
        FuncionariosTela telaFunc = new FuncionariosTela();
        telaFunc.setVisible(true);
   
    }//GEN-LAST:event_jButtonFuncionariosActionPerformed

    //instanciando a classe ObrasTela através do botão e deixando o jFrame visivel
    private void jButtonObrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonObrasActionPerformed
        ObrasTela obras = new ObrasTela();
        obras.setVisible(true);
    }//GEN-LAST:event_jButtonObrasActionPerformed
    
    //instanciando a classe FerramentasTela através do botão e deixando o jFrame visivel
    private void jButtonFerramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFerramentasActionPerformed
        FerramentasTela ferramentas = new FerramentasTela();
        ferramentas.setVisible(true);
    }//GEN-LAST:event_jButtonFerramentasActionPerformed

    private void jButtonMateriaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMateriaisActionPerformed
        MateriaisTela materiais = new MateriaisTela();
        materiais.setVisible(true);
    }//GEN-LAST:event_jButtonMateriaisActionPerformed
    
    //instanciando a classe AlvenariaTela através do botão e deixando o jFrame visivel
    private void jButtonCalcularAlvenariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalcularAlvenariaActionPerformed
        AlvenariaTela alvenaria = new AlvenariaTela();
        alvenaria.setVisible(true);
        
    }//GEN-LAST:event_jButtonCalcularAlvenariaActionPerformed

    //instanciando a classe CalcularContraPiso através do botão e deixando o jFrame visivel
    private void jButtonContrapisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContrapisoActionPerformed
        CalcularContraPiso cp = new CalcularContraPiso();
        cp.setVisible(true);
    }//GEN-LAST:event_jButtonContrapisoActionPerformed

    //instanciando a classe Reboco através do botão e deixando o jFrame visivel
    private void jButtonRebocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRebocoActionPerformed
        Reboco reboco = new Reboco();
        reboco.setVisible(true);
    }//GEN-LAST:event_jButtonRebocoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalcularAlvenaria;
    private javax.swing.JButton jButtonContrapiso;
    private javax.swing.JButton jButtonFerramentas;
    private javax.swing.JButton jButtonFuncionarios;
    private javax.swing.JButton jButtonMateriais;
    private javax.swing.JButton jButtonObras;
    private javax.swing.JButton jButtonReboco;
    private javax.swing.JLabel jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
